### ISSUE TITLE
Problem-Error downloading ERTflix videos

### ISSUE THREAD

**Issue by PaNoRaMiX-Gr** [AngelouD/ert-downloader#15]
hello mr, 
i'm trying download this link " https://www.ertflix.gr/xenes-seires/to-mikro-spiti-sto-livadi-s04ep10v-o-machitis-meros-v/?series=to-mikro-spiti-sto-livadi " and i receive this error
![ertflix](https://user-images.githubusercontent.com/87739421/126414656-3ca30d7e-9933-4b75-9ae0-86450a8e4c6f.jpg)

the same with this link too, similar error " https://www.ertflix.gr/xenes-seires/to-mikro-spiti-sto-livadi-s04ep11-tha-synantithoyme-sto-panigyri/?series=to-mikro-spiti-sto-livadi "

for previous episodes, working fine, but for these last two it has these errors... i'll try tommorow to download the new ones they will upload and i'll write again.

thank you very much for your work! hope fix it soon ;)

**Comment by AngelouD** [comment]
The newest update must have solved any problems with ertflix.

**Comment by AngelouD** [comment]
Could probably be an error mention on this issue https://github.com/AngelouD/ert-downloader/issues/17#issuecomment-940064843 fixed with a2f02a08bd2b71b80175cd11a2fc72b5146160f3 ?
