### ISSUE TITLE
Πώς χρησιμοποιώ όλα αυτά τα αρχεία;

### ISSUE THREAD

**Issue by Rivend3ll** [AngelouD/ert-downloader#17]
Κατέβασα το πακέτο με τα αρχεία που υπάρχουν εδώ κι έχω κατεβάσει και το ffmpeg, που μέσω ενός tutorial video το πέρασα στον υπολογιστή. Από δω και πέρα πώς χρησιμοποιώ τα αρχεία του πακέτου για να κατεβάσω βίντεο από το ertflix (ή από άλλα τηλεοπτικά κανάλια);
Αρχάριος σε αυτά... Μπορεί κανείς να μου πει step by step τα βήματα;

**Comment by AngelouD** [comment]
Αφου ειναι όλα σε έναν φάκελο πατάς δεξί κλίκ σε κάποιο κενό χώρο του φακέλου πατώντας ταυτόχρονα shift. Κάπου θα λέει για powershell ή γραμμή εντολών/command prompt. Θα σου ανοιξει ενα παράθυρο. Απο εκεί γράφεις `python ert-downloader.py link` οπου link η διεθυνση του βιντεο που θες να κατεβασεις.

Πρεπει να εχεις εγκαταστήσει πρωτα τη python, σε αυτό το παραθυράκι πριν τρέξεις αυτα που είπα πριν τρέξε πρώτα ενα `pip install -r requirements.txt`

**Comment by Rivend3ll** [comment]
Έχω κατεβάσει κι εγκαταστήσει την Python μέσω του python-3.10.0-amd64.exeΑπό τη startbar (Win10 x64):


κι όταν δοκίμασα την παραπάνω εντολή python ert-downloader.py και το link
βγήκε αυτό το μήνυμα:

κι όταν δοκίμασα -πάλι από το Powershell- την εντολή pip, βγήκε αυτό:










 

    On Saturday, October 9, 2021, 11:58:32 PM GMT+3, Dimitris Angelou ***@***.***> wrote:  
 
 


Αφου ειναι όλα σε έναν φάκελο πατάς δεξί κλίκ σε κάποιο κενό χώρο του φακέλου πατώντας ταυτόχρονα shift. Κάπου θα λέει για powershell ή γραμμή εντολών/command prompt. Θα σου ανοιξει ενα παράθυρο. Απο εκεί γράφεις python ert-downloader.py link οπου link η διεθυνση του βιντεο που θες να κατεβασεις.

Πρεπει να εχεις εγκαταστήσει πρωτα τη python, σε αυτό το παραθυράκι πριν τρέξεις αυτα που είπα πριν τρέξε πρώτα ενα pip install -r requirements.txt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dkyrgia** [comment]
Καλησπέρα,
Προσπαθώ να κατεβάσω από το ertflix
Δίνω την εντολή και τρέχει
python ert-downloader.py https://www.ertflix.gr/vod/vod.163247-theia-leitourgia

Η απάντηση είναι η εξής: (οι παύλες είναι δικές μου προφανώς)
----------------------------------------------------------------
Θεία Λειτουργία
Θεία Λειτουργία
Διαλέξτε επιθυμητή ανάλυση | Select wanted format
-----------------------------------------------------------------
Δε γυρνάει κανένα λινκ
Μένει έτσι εκεί για ώρα πολλή
Από ότι είδα στον κώδικα σου περιμένουμε να επιστρέψει λινκ(ς)
αριθμημένα και θα πληκτρολογήσω αριθμό (int)
Ότι αριθμό και να δώσω γυρνάει  IndexError: list index out of range
γιατί προφανώς η λίστα μένει άδεια

Θεωρώ ότι κάνει parse τη σελίδα που του δίνω γιατί τα Ελληνικά (Θεία Λετουργία) 
τα γυρνάει το πρόγραμμα 
Τα 3 εκτελέσιμα του ffmpeg τα έχω βάλει στον ίδιο φάκελλο με το python ert-downloader.py
Το τρέχω σε Windows 10 με python 3.9.2
Έτρεξα και το pip install -r requirements.txt γιατί μερικές βιβλιοθήκες μου λείπανε

Καμία ιδέα ?

Σε ευχαριστώ 
Δημήτρης
και ευχαριστώ όπως και να έχει για τον κώδικα !!

**Comment by dkyrgia** [comment]
Θα προχωρήσω σε 2η ερώτηση
Δούλεψε μια χαρά και κατέβηκε!
Κατέβασε πολλά κομμάτια και στο τέλος τα έδεσε όλα μαζί
Έβγαζε όμως αυτά τα μηνύματα (συνημμένο)
![Clipboard01](https://user-images.githubusercontent.com/7116912/136835955-ffe7a18d-6b44-441a-82f2-89dde4d83aea.jpg)
Εϊναι πρόβλημα? Πρέπει να κάνω κάτι για αυτό?
Το βίντεο δείχνει καλό αλλά δεν το έχω locally για να είμαι σίγουρος ότι είναι οκ
δουλεύω με anydesk σε απομακρυσμένο γιατί ε΄χει πολύ καλή γραμμή και είναι δυνατό μηχανάκι

Να είσαι καλά
Δημήτρης
