### ISSUE TITLE
Όταν κατεβάζεις βίντεο από ΕΡΤflix ξέρει κανείς γιατί σου βγάζει σε κάποια επεισόδια σφάλμα;

### ISSUE THREAD

**Issue by Rivend3ll** [AngelouD/ert-downloader#19]
Σε κάποια επεισόδια μου βγάζει το εξής σφάλμα, ενώ πχ το μεθεπόμενο επεισόδιο το κατεβάζει κανονικά.
Το πρόβλημα έχει ως εξής: Δεν βγάζει επιλογές για ανάλυση βίντεο (720p, 1080p, κλπ.) όπως κάνει γενικά και στο τέλος βγάζει τα συγκεκριμένα μηνύματα και δεν κατεβάζει καν το επεισόδιο.
Ξέρει κανείς καμιά λύση;

![ερτ 1](https://user-images.githubusercontent.com/92221963/138534343-fe905356-bfa2-4b21-8ef8-3c199fcf037a.JPG)

**Comment by AngelouD** [comment]
Just redownload the project, the new update has probably fixed the issue.
