### ISSUE TITLE
index out of range line 42

### ISSUE THREAD

**Issue by nkour** [AngelouD/ert-downloader#2]
tried with https://series.ert.gr/i-yperochi-fili-moy-s1-ep1/ did not work. 

tried to print(playlist_m3u8.split('\n'))
list is empty

**Comment by AngelouD** [comment]
It works for me.

Do you by any chance live abroad? The request made contained the geolocation of the user, and in the domain series.ert it sometimes needed a different url at the request to work.

line 36:
`try:  # fixing geolocation issue for some videos
        chunklist_url = playlist_m3u8.split('\n')[3]
        playlist_m3u8 = requests.get(url_root + 'playlist.m3u8', verify=False).text
    except:
        url_root = url_root.replace('dvrorigin/', 'dvrorigingr/')
        playlist_m3u8 = requests.get(url_root + 'playlist.m3u8', verify=False).text
        chunklist_url = playlist_m3u8.split('\n')[3]`

**Comment by nkour** [comment]
I was in Windoz. Tried now in Linux seems to work althought I would appreciated some kind of progress indication. bravo an akoma ise mathitis kalo script!

**Comment by AngelouD** [comment]
It worked for me in windows, weird problem. I could only replicate it by implementing proxy support ([see](https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module), and using a foreign proxy. A remedy would be to use a Proxy when using the program from non-greek ip's(being outside of Greece, or using VPN's) but that's illegal, so I cant implement it, but that's probably not the problem you encountered. Thanks, and yes I am a student at the university I always wanted!
