### ISSUE TITLE
python 3.8

### ISSUE THREAD

**Issue by nikdimster** [AngelouD/ert-downloader#20]
C:\Users\user\Desktop\Νέος φάκελος\ert-downloader-master>python ert-downloader.py https://www.ertflix.gr/*****
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Νέος φάκελος\ert-downloader-master\ert-downloader.py", line 1, in <module>
    from extractors import archive_extractor, ertflix_extractor, star_extractor, megatv_extractor
  File "C:\Users\user\Desktop\Νέος φάκελος\ert-downloader-master\extractors\archive_extractor.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by AngelouD** [comment]
You have not run on the terminal `pip install -r requirements.txt`

**Comment by nikdimster** [comment]
Thanks for the prompt reply
Running python ert-downloader.py https://www.ertflix.gr/****
Many small snapshots are downloaded that in the end do not merge.

**Comment by nikdimster** [comment]
The second time I tried it came down normally, thank you very much!!!!
