### ISSUE TITLE
Downloads trailer, not movie

### ISSUE THREAD

**Issue by renovatio118** [AngelouD/ert-downloader#21]
Καλησπέρα & καλό μήνα!
Δοκιμάζοντας το πρόγραμμα με ένα Ertflix URL, κατεβάζει το trailer από τη σελίδα και όχι την ταινία.
Χρειάζεται κάποια συγκεκριμένη εντολή για το πιό βίντεο να κατεβάσει; 

Ευχαριστώ πολύ.

**Comment by AngelouD** [comment]
Can you provide me the link you are experiencing the problem with?

**Comment by renovatio118** [comment]
> Can you provide me the link you are experiencing the problem with?

Of course. Here it is: `https://www.ertflix.gr/vod/vod.166230-100-ekatomuria-views`

**Comment by AngelouD** [comment]
I can reproduce, I will try to push a fix tomorrow.

**Comment by renovatio118** [comment]
> I can reproduce, I will try to push a fix tomorrow.

Thank you very much. Great tool by the way, amazing work!

**Comment by AngelouD** [comment]
Fixed with 3eaa6f4cbe30427e3891e465c09713f6a41e55d2

Check for yourself to verify.

**Comment by renovatio118** [comment]
> Fixed with [3eaa6f4](https://github.com/AngelouD/ert-downloader/commit/3eaa6f4cbe30427e3891e465c09713f6a41e55d2)
> 
> Check for yourself to verify.

Yes, works perfectly now! Thank you very much for the quick fix, i really appreciate it!
