### ISSUE TITLE
Κατεβαίνει το επόμενο επεισόδιο απ'ότι έχει επιλεγεί

### ISSUE THREAD

**Issue by balarinios** [AngelouD/ert-downloader#22]
Κατ'αρχήν να σημειώσω ότι έχεις κάνει εξαιρετική δουλειά! -) 

Ένα μικρό σχόλιο, όταν τρέχει το script και φέρνει τη λίστα με τα επεισόδια, ζητάει από το χρήστη να επιλέξει το επεισόδιο που θέλει να κατεβάσει. Μετά το entry του χρήστη, το script κατεβάζει πάντα το επόμενο επεισόδιο από αυτό που επέλεξε ο χρήστης!

Συγχαρητήρια και πάλι για την πολύ καλή δουλειά!

**Comment by AngelouD** [comment]
Are you sure you are selecting the number contained in the brackets?

ex
`
[0] 1 - Title
[1] 2 - Title
[2] 3 - Title
`

you will have to select 1 for episode 2

**Comment by balarinios** [comment]
Ah ok, i understand now. It would be more straightforward to type the number of the episode directly, but ok this also works. Thanks a lot for the clarification!
