### ISSUE TITLE
Πρόβλημα που σχετίζεται με τον τίτλο του επεισοδίου.

### ISSUE THREAD

**Issue by michladis** [AngelouD/ert-downloader#23]
Όταν το όνομα του επεισοδίου περιλαμβάνει μη επιτρεπτούς χαρακτήρες (πχ : ), ενώ φαίνεται να κατεβάζει τα κομμάτια, καταλήγει σε μηδενικό αρχείο με όνομα μέρος του ονόματος, μέχρι τον μη επιτρεπτό χαρακτήρα.

Για παράδειγμα: https://www.ertflix.gr/series/ser.166218-o-khoros-ten-epeiron, και επιλογή [0] ή [2].

BTW, συγχαρητήρια για την υπέροχη δουλειά.

**Comment by AngelouD** [comment]
Fixed with 2f3083f7fa795085b8cadfb7a2511b62108d1daa
