### ISSUE TITLE
Αποτυχία κατεβάσματος επεισοδίου

### ISSUE THREAD

**Issue by michladis** [AngelouD/ert-downloader#24]
Το κατέβασμα επεισοδίου αποτυγχάνει, ίσως εξ' αιτίας του τρόπου δημιουργίας του ονόματος του αρχείου (κάποιο κρυφό tab, δεν είμαι σίγουρος).
Για αναπαραγωγή του σφάλματος: https://www.ertflix.gr/series/ser.168677-bolta-sten-arkhaia-aigupto και επιλογή 1.

**Comment by AngelouD** [comment]
Fixed: 48160e3e883ae82e2f5ee2fff56bd72d290e7011
