### ISSUE TITLE
Ertflix: Episode not available, please check if episode is available on platform. If it is open an issue on github.

### ISSUE THREAD

**Issue by PavlosIsaris** [AngelouD/ert-downloader#28]
Hi, when I try to download a documentary from ertflix, I get the following error:

`Episode not available, please check if episode is available on platform. If it is open an issue on github.`

An example that fails is [this](https://www.ertflix.gr/en/vod/vod.190847-to-noema-tes-zoes#.YnQT_8twWAg.link).

![image](https://user-images.githubusercontent.com/6071000/166993196-144b3c7a-ef1c-478b-8061-048fa69f10d0.png)

`python version: 3.10.4`

**Comment by dmavroeidis** [comment]
This can happen sometimes when your browser has kept the page content it its cache. So, if you see this message again, and the web page still loads, try refreshing your browser after having expunged the cache.
