### ISSUE TITLE
Select Wanted Quality vs True Quality? 

### ISSUE THREAD

**Issue by saligari** [AngelouD/ert-downloader#29]
Πολύ χρήσιμο το πρόγραμμα! 

Στην "επιθυμητή ανάλυση" που βρίσκει το πρόγραμμα HD & FHD αναλύσεις, σε σειρές/επεισόδια που είναι παλιά και η πραγματική ανάλυσή τους είναι χαμηλότερη, επιλέγοντας την 1920*1080 πχ το βίντεο δεν μπορεί να έχει καλύτερη ανάλυση ουσιαστικά αλλά ως αρχείο είναι πολύ μεγαλύτερο. Ή τουλάχιστον έτσι καταλαβαίνω, τώρα στον ήχο μπορεί να έχει όντως διαφορά δεν ξέρω; Υπάρχει κάποιος τρόπος να βρω ποια είναι η πραγματική/αρχική ανάλυση; (γιατί καταλαβαίνω μάλλον δεν έχει νόημα να κατεβάσω κάτι σε FHD όταν έχει γραφτεί ούτως ή άλλως σε χαμηλότερη ποιότητα.)

Και side-question πώς μπορώ να κάνω auto-input για να τρέξει να κατεβάσει και το πρώτο και το δεύτερο επεισόδιο από το ίδιο link/σειρά, σε δεδομένη ανάλυση; Δηλαδή να τρέξει αυτόματα την ίδια εντολή και μετά να πατήσει 1 αντί για 0.

Ευχαριστώ!

**Comment by AngelouDi** [comment]
1. Η ανάλυση που προσφέρεται έρχεται απο το API της ΕΡΤ. Δεν νομίζω να υπάρχει τρόπος να φανεί ποιά είναι η πραγματική.
2. Προς το παρόν δεν υπάρχει, αμα βρω χρόνο θα προσπαθήσω να το βάλω.

**Comment by saligari** [comment]
Thanks!
